### ISSUE TITLE
Open API Spec does not take in account host and Port 

### ISSUE THREAD

**Issue by ads69** [FMXExpress/AutoTablesForRADServer#2]
Open API Spec Doesn't take in account Host and Port.

I have this when trying to call a method in the last TabSheet of the editor

`curl -X GET "http://example.com/v1getusers/" -H  "accept: application/xml"`

instead of http://localhost:8080/v1/getusers/

Note here the Host, the port and v1 (separated by a "/")

**Comment by FMXExpress** [comment]
I uploaded an update.

**Comment by ads69** [comment]
It seems better but now I have  curl -X GET "http://localhost:8080/v1getclient/" -H  "accept: application/xml" instead of curl -X GET "http://localhost:8080/v1/getclient/" -H  "accept: application/xml"

note the (/) after v1


Also now AutoTablesClientDM.Login id called but Login nor Logout method are created in AutoTablesClientDM

**Comment by FMXExpress** [comment]
Fixed.
